### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by k47ha** [behinger/etcomp#11]
# parse_message
- after splitting the msg string all . , and : get removed
- [x] is **total** a good variablename for describing which Grid we are using? (maybe a shorter form of total_grid_points or grid_type or grid_size or something else?)
- [x] is the string 'block' missing for the message ['GRID', 'stop', (?block?). '1']
- [x] what about the condition head rotate roll?  (There are no samples in the test data: did we fix the confusion on what is what?)
- [x] I didn't parse for: Instruction, Finished. Should I?
- [x] no samples for: ConnectPupil, Roll   

- [x] Can we talk again about how to encode the small Grid before / after?  do we need more information for GRID in the df than   msg_time, exp_event: experimental event of GRID (buttonpress, element, start, stop), block,  and for GRID element: element,  posx/posy,  total (grid_size)
- [x] Is the angle of YAW rotation encoded in the trailnumber? or should we send that info in the message?
- [x] why can I find YAW msgs in pupillabs msgs but not in EyeLink?

# dataframes

- we were not consistent with having a pd_ in front of a variable if it is a df
--> removed all pd_   as the df are always panda dataframes

## samples
- [x] should the **samples** dataframe only have the columns smpl_time, gx, gy or also "confidence"?
--> is there an equivalent to confidence for eyelink? what is it called?

## "full"

**Comment by k47ha** [comment]
Here is also a (not very pretty) pdf  to visualize the dataframes:
[overview_df.pdf](https://github.com/behinger/etcomp/files/1956360/overview_df.pdf)

**Comment by k47ha** [comment]
Cant find data for tilt in plmsgs and also less instructions etc..
Am I thinking the wrong way when expecting that both pl and el should get the same messages?

![screenshot from 2018-05-02 16-28-03](https://user-images.githubusercontent.com/27031599/39529077-1a8dbcd8-4e26-11e8-8fc3-5ec34e00e4e2.png)

**Comment by behinger** [comment]
Will check tilt could be same problem  as rotate. Different number in instruct us because when recordings are started /stopped

Am 2. Mai 2018 16:30:24 MESZ schrieb K Gross <notifications@github.com>:
