### ISSUE TITLE
papers to cite

### ISSUE THREAD

**Issue by behinger** [behinger/etcomp#17]
Comparing eye trackers by correlating their eye-metric data

**Comment by behinger** [comment]
Common predictors of accuracy, precision and data loss in 12 eye-trackers <-- eyelink accuracy of 1° (as we observe as well)

**Comment by behinger** [comment]
Sampling frequency and eye-tracking measures: how speed
affects durations, latencies, and more

To argue why we did not downsample the eyelink

**Comment by behinger** [comment]
https://link.springer.com/article/10.3758/s13428-017-0954-y

**Comment by k47ha** [comment]
> https://link.springer.com/article/10.3758/s13428-017-0954-y

ist jetzt im zotero/overleaf
