### ISSUE TITLE
POM Peter Issues to discuss

### ISSUE THREAD

**Issue by behinger** [behinger/etcomp#20]
Unordered:

- HMM vs. EM vs. uneye(Anna, into the wild => smooth pursuit)
- Microsaccades, optimize parameter?
- Smooth pursuit: model on velocity or position
- Smooth pursuit: make the model hierarchical?
- Pupil dilation: How to report individual differences
- Calibration: Remove blocks with calibration< 1.5 / 0.5?
- Statistics: How much statistics? 
- Aggregation metric: mean / median / mean, or winsorized/winsorized/winsorized?
   - how to handle in statistics? I used robust regression, showed me approx. the mean/median/mean results
- add the undistortion from camera for pupil labs

**Comment by k47ha** [comment]
rms vs. sd
