### ISSUE TITLE
Structure of experiment

### ISSUE THREAD

**Issue by behinger** [behinger/etcomp#3]
## Functions we need
- draw_target(x,y,whichTarget)
   - whichTarget => flag, fixationCross or pupillabs image
- flip_screen(win)
  - Add QR-code before Screen('Flip',win)
- synch_et(taskname) / synch_et(eventname,x,y)
  - send notificaiton to both ETs
  -    Eyelink('message','task %s', taskname);
- randomization (one one time call)
  - also calculate which images to show in which order
  - return structure with sequences for 7x7 grid, 13x13 grid
- draw_instructions(win,taskname)
  -  possibility to play movie / gif (if easy in PTB)
- win = init_screen()
- EL = init_eyelink(win)
- PL = init_pupillabs()

## Main script

- init screen
- init Eyelink
- init Pupillabs
- load randomization
- for repeats
  - calibration (with pupil targets) <-> validation (<0.5° mean <1° max eyelink, pupillabs??
  - large grid (7x7)
  - smooth pursuit
    - 1 s per line
    - 13 point(?, planned was 7x7, but could take very long)
  - free viewing images (3 images) --> potsdam or zürich?
    - don't repeat images, same images for all subjects
  - microsaccade / fixation cross
  - blinks (MakeBeep, => ask rene)
  - pupil dilation (5 levels, 0,64,128,192,256 => balanced semi-random changes)
     - no repeats in sequence
  - small grid (13 punkt calibration eyelink)
  - Yaw Head Motion
     - Animation of face
  - roll
     - Animation of face
  - small  grid (13 point)

  

13-Point Grid:
```matlab

% % Set custom calibration options
% % layout on screen for 9 points:
% % 5    1    6
% %   9    10
% % 3    0    4
% %   11   12
% % 7    2    8

% % the pixel coordinates

% scr_h = 1024 example,value given
% scr_w = 1920 example,value given
% left, left-middle, middle, middle right right
l = scr_w/2 + (-2*scr_w/8);
lm = scr_w/2 + (-1*scr_w/8);
m = scr_w/2 + (0*scr_w/8);
mr = scr_w/2 + (1*scr_w/8);
r = scr_w/2 + (2*scr_w/8);
% % top, top-center, center, center-bottom, bottom
t  =  scr_h/2 + (-2*scr_h/8);
tc = scr_h/2 + (-1*scr_h/8);
c  = scr_h/2 + (0*scr_h/8);
cb = scr_h/2 + (1*scr_h/8);
b  = scr_h/2 + (2*scr_h/8);
```

**Comment by IngaIbs** [comment]
Todo
- [ ] change coordinates for 13 point
- [ ] adjust image size (screen dependent), stimulus times
- [ ] build randomizations for small grid, large grid, images, smooth pursuit, pupil dilation
- [ ] choose stimuli
