### ISSUE TITLE
zmq_request SCRIPT not FUNCTION

### ISSUE THREAD

**Issue by tere93** [behinger/etcomp#31]
Hi there,

 Super helpful code you guys put together. I'm trying to run ETcomp.m but it keeps givng me the following error in this part:

            zmq_request('init');
Error:
            Attempt to execute SCRIPT zmq_request as a function:
            /Users/teresa/Desktop/etcomp/experiment_ehinger2019/zmq/zmq_request.mError 
            using ETcomp (line 63)

I looked at the code zmq_request.m inside 'zmq' folder and it seems to be an all commented out script, and not a function. Can you give me a hand here?

Thanks!

**Comment by shoeffner** [comment]
I am not sure, as I haven't tried myself yet, but it could be that you have to compile the zmq_request using https://github.com/behinger/etcomp/blob/master/experiment/zmq/compile.m (instructions are inside the file). There is also a test file https://github.com/behinger/etcomp/blob/master/experiment/zmq/zmq_test_bene.m.

**Comment by behinger** [comment]
yes I think that should be right. Try to compile it.

Disclaimer: I am not the maintainer of cosy zmq: https://github.com/UCLouvain-IoNS-CATL/cosy-zeromq-matlab

**Comment by tere93** [comment]
fixed it! I was having a hard time compiling it in windows but it works fine in Ubuntu 18.04. thanks!

**Comment by behinger** [comment]
there are bunch of zmq toolkits for matlab, I hard a hard time getting any other to run on linux ;-) So maybe there is a working one for each OS ;)

Glad it worked!
